apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
spec:
  template:
    spec:
      serviceAccountName: {serviceAccount}
      containers:
        - name: {name}
          image: ""
          volumeMounts: []
          env: []
          ports:
          - name: notebook-port
            containerPort: 
            protocol: TCP
          resources:
            requests:
              cpu: "0.1"
              memory: "0.1Gi"
      volumes: []
      tolerations: []
