apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: namespace-labels
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: namespace-labels-data
      containers:
      - command:
        - /manager
        - "-userid-header"
        - $(USERID_HEADER)
        - "-userid-prefix"
        - $(USERID_PREFIX)
        - "-workload-identity"
        - $(WORKLOAD_IDENTITY)
        envFrom:
          - configMapRef:
              name: config
        volumeMounts:
        - name: namespace-labels
          mountPath: /etc/config/labels
          readOnly: true
        image: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
        imagePullPolicy: Always
        name: manager
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
        - containerPort: 8080
          name: manager-http
          protocol: TCP
      serviceAccountName: controller-service-account
