apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
spec:
  template:
    spec:
      affinity: {{}}
      serviceAccountName: {serviceAccount}
      containers:
        - name: {name}
          image: ""
          volumeMounts: []
          env: []
          resources:
            requests: {{}}
            limits: {{}}
          ports: []
      ttlSecondsAfterFinished: 300
      tolerations: []
      volumes: []
